-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4cvv6oiQ2d4LDmKo
xc+Ky8EWwZEXcc2cKNlEUTUaVVSgCgYIKoZIzj0DAQehRANCAARLngcFpkdN4ffv
EwmTpFHpvnyG/EJTyY/9sxNWbbgxa56qXtMItdxcjEH4yi0NeRzIbSAUfqf4HyB4
v7UoAvYw
-----END PRIVATE KEY-----